FROM nginx:latest

COPY ./dist /usr/share/nginx/html
COPY ./src/assets /usr/share/nginx/html/src/assets
COPY ./favicon.png /usr/share/nginx/html/src/favicon.png

COPY ./nginx/dev/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/dev/default.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]
