FROM openjdk:17
ARG JAR_FILE=tteoksang*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./tteoksangBackend.jar
ENV TZ=Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "./tteoksangBackend.jar"]
