version: '3'

services:
  redis1:
    image: redis:7.2.4
    container_name: TteoksangRedis-1
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6379
    volumes:
      - redis-data:/data
    networks:
      - TteoksangNetwork
    ports:
      - "6379:6379"
    command: ["redis-server", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--appendfilename", "redis1.aof", "--auto-aof-rewrite-percentage", "100", "--auto-aof-rewrite-min-size", "64mb", "--save", ""]

  redis2:
    image: redis:7.2.4
    container_name: TteoksangRedis-2
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6380
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    networks:
      - TteoksangNetwork
    depends_on:
      - redis1
    command: ["redis-server", "--port", "6380", "--masterauth", "${REDIS_PASSWORD}", "--replicaof", "redis1", "6379", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--appendfilename", "redis2.aof", "--auto-aof-rewrite-percentage", "100", "--auto-aof-rewrite-min-size", "64mb", "--save", ""]

  redis3:
    image: redis:7.2.4
    container_name: TteoksangRedis-3
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6381
    ports:
      - "6381:6381"
    volumes:
      - redis-data:/data
    networks:
      - TteoksangNetwork
    depends_on:
      - redis1
    command: ["redis-server", "--port", "6381", "--masterauth", "${REDIS_PASSWORD}", "--replicaof", "redis1", "6379", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--appendfilename", "redis3.aof", "--auto-aof-rewrite-percentage", "100", "--auto-aof-rewrite-min-size", "64mb", "--save", ""]

  redis-sentinel1:
    image: bitnami/redis-sentinel:7.0.15
    container_name: TteoksangRedisSentinel1
    restart: unless-stopped
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=${REDIS_MASTER}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PORT_NUMBER=26379
    ports:
      - '26379:26379'
    networks:
      - TteoksangNetwork
    depends_on:
      - redis1
      - redis2
      - redis3

  redis-sentinel2:
    image: bitnami/redis-sentinel:7.0.15
    container_name: TteoksangRedisSentinel2
    restart: unless-stopped
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=${REDIS_MASTER}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PORT_NUMBER=26380
    ports:
      - '26380:26380'
    networks:
      - TteoksangNetwork
    depends_on:
      - redis1
      - redis2
      - redis3

  redis-sentinel3:
    image: bitnami/redis-sentinel:7.0.15
    container_name: TteoksangRedisSentinel3
    restart: unless-stopped
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=${REDIS_MASTER}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PORT_NUMBER=26381
    ports:
      - '26381:26381'
    networks:
      - TteoksangNetwork
    depends_on:
      - redis1
      - redis2
      - redis3

  mariaDB:
    image: mariadb:10.11.7
    container_name: TteoksangMariaDB
    restart: unless-stopped
    volumes:
      - mariadb-data:/lib/var/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - TteoksangNetwork
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  mongoDB:
    image: mongo:7.0
    container_name: TteoksangMongoDB
    restart: unless-stopped
    volumes:
      - mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: TteoksangMongoExpress
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: TteoksangMongoDB
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_USER_PASSWORD}

  mongo-initializer:
    image: ssuyas/tteoksang-initializer
    container_name: TteoksangInitializer
    environment:
      MONGO_DB_ROOT_USER_NAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_DB_ROOT_USER_PASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      HOST_NAME: ${HOST_NAME}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./mongodb/filtered_season_event.json:/event.json
    command: ["/bin/sh", "-c", "mongoimport --username=MONGO_DB_ROOT_USER_NAME --password=MONGO_DB_ROOT_USER_PASSWORD --host=$HOST_NAME --port=27017 --drop --db=$DB_NAME --collection=event --file=event.json --jsonArray --authenticationDatabase=admin"]

  zookeeper:
    image: bitnami/zookeeper:3.8.3
    container_name: TteoksangZookeeper
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - TteoksangNetwork

  kafka:
    image: bitnami/kafka:3.6
    container_name: TteoksangKafka
    restart: unless-stopped
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://TteoksangKafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - TteoksangNetwork
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  redis-data:
    driver: local
  mariadb-data:
  zookeeper-data:
  kafka-data:
  mongodb-data:

networks:
  TteoksangNetwork:
    external: true

