version: '3.7'

services:
  TteoksangBackendDev:
    image: ssuyas/tteoksang_backend_dev
    container_name: TteoksangBackendDev
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      DB_URL: ${DB_URL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      AUTH_REDIRECT_URL: ${AUTH_REDIRECT_URL}
      JWT_KEY: ${JWT_KEY}
      TURN_PERIOD_SEC: ${TURN_PERIOD_SEC}
      TURN_PERIOD: ${TURN_PERIOD}
      BUYABLE_PRODUCT_TURN_PERIOD: ${BUYABLE_PRODUCT_TURN_PERIOD}
      EVENT_ARISE_TURN_PERIOD: ${EVENT_ARISE_TURN_PERIOD}
      EVENT_ARISE_INITIAL_TURN: ${EVENT_ARISE_INITIAL_TURN}
      NEWS_PUBLISH_INITIAL_TURN: ${NEWS_PUBLISH_INITIAL_TURN}
      HALF_YEAR_BREAK_SEC: ${HALF_YEAR_BREAK_SEC}
      QUARTER_YEAR_TURN_PERIOD: ${QUARTER_YEAR_TURN_PERIOD}
      SEASON_START_DATE: ${SEASON_START_DATE}
      SEASON_YEAR_PERIOD: ${SEASON_YEAR_PERIOD}
      RENT_FEE: ${RENT_FEE}

  TteoksangRedisDev:
    image: redis:7.2.4
    container_name: TteoksangRedisDev
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-dev-data:/data

  TteoksangMariaDBDev:
    image: mariadb:10.11.7
    container_name: TteoksangMariaDBDev
    restart: unless-stopped
    volumes:
      - mariadb-dev-data:/lib/var/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  TteoksangFrontendDev:
    image: ssuyas/tteoksang_frontend_dev
    container_name: TteoksangFrontendDev
    restart: unless-stopped
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    expose:
      - "443:443"
      - "80:80"

  mongoDB-dev:
    image: mongo:7.0
    container_name: TteoksangMongoDBDev
    restart: unless-stopped
    volumes:
      - mongodb-dev-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "27017:27017"

  mongo-express-dev:
    image: mongo-express
    container_name: TteoksangMongoExpressDev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: TteoksangMongoDB
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_USER_PASSWORD}

  mongo-initializer:
    image: ssuyas/tteoksang-initializer
    container_name: TteoksangInitializerDev
    environment:
      MONGO_DB_ROOT_USER_NAME: ${MONGO_DB_ROOT_USER_NAME}
      MONGO_DB_ROOT_USER_PASSWORD: ${MONGO_DB_ROOT_USER_PASSWORD}
      HOST_NAME: ${HOST_NAME}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./event.json:/event.json
    command: [ "/bin/sh", "-c", "sleep 10 && mongoimport --username=$MONGO_DB_ROOT_USER_NAME --password=$MONGO_DB_ROOT_USER_PASSWORD --host=$HOST_NAME --port=27017 --drop --db=$DB_NAME --collection=event --file=event.json --jsonArray --authenticationDatabase=admin" ]
    depends_on:
      - mongoDB-dev
volumes:
  redis-dev-data:
  mariadb-dev-data:
  mongodb-dev-data:

networks:
  default:
    external: true
    name: TteoksangNetworkDev