FROM openjdk:17
ARG JAR_FILE=data*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./tteoksangData.jar
ENV TZ=Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "./tteoksangData.jar"]
