spring:
  messages:
    basename: errors, messages
    encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-dev.yml
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${USER_NAME}
      password: ${USER_PASSWORD}
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 30000
      connection-test-query: SELECT 1
      isolate-internal-queries: false
      validation-timeout: 5000
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      sentinel:
        master: ${REDIS_MASTER}
        nodes: ${REDIS_SENTINEL_HOST}:${REDIS_SENTINEL_NODE1_PORT}, ${REDIS_SENTINEL_HOST}:${REDIS_SENTINEL_NODE2_PORT}, ${REDIS_SENTINEL_HOST}:${REDIS_SENTINEL_NODE3_PORT}
      port: 26379
      password: ${REDIS_PASSWORD}
      timeout: 600ms
    mongodb:
      database: ${DB_NAME}
      port: 27017
      user: ${MONGO_DB_ROOT_USER_NAME}
      password: ${MONGO_DB_ROOT_USER_PASSWORD}
      uri: mongodb://${MONGO_DB_ROOT_USER_NAME}:${MONGO_DB_ROOT_USER_PASSWORD}@${HOST_NAME}:27017/${DB_NAME}?authSource=admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jwt:
    secret: ${JWT_KEY}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URL}
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      welcome:
        tteoksang: debug
    org.springframework.security: DEBUG

social:
  google:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect: ${GOOGLE_REDIRECT_URL}

ingame:
  period:
    turn: ${TURN_PERIOD}
    event: ${EVENT_ARISE_PERIOD}
    half-year: ${HALF_YEAR_PERIOD}
    half-year-report: ${HALF_YEAR_REPORT_PERIOD}
    season: ${SEASON_PERIOD}
  cron:
    season-start: ${SEASON_START_DATE}
  time:
    event-start: ${EVENT_ARISE_TIME}
    news-start: ${NEWS_PUBLISH_TIME}

auth-redirect-url: ${AUTH_REDIRECT_URL}

server:
  port: 8080